---
- name: Network Getting Started First Playbook
  connection: local
  gather_facts: false
  hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Install docker daemon dependencies
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common

    - name: Install Docker's APT key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg

    - name: Add Docker's APT repo
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu  bionic  stable
        state: present

    - name: Install Docker (!)
      apt:
        name: "docker-ce"
        state: present
    
    - name: Test Docker
      shell:
        cmd: sudo docker version
